package com.problems;

import java.util.Scanner;

public class Anybase_addition {
    public static void main(String[] args) {
        Scanner sc= new Scanner(System.in);
        int b=sc.nextInt();
        int n1=sc.nextInt();
        int n2=sc.nextInt();

        int d=getsum(b,n1,n2);
        System.out.println(d);


    }
    public static int getsum(int b,int n1,int n2){
        int rv=0; //last value
        int carr=0; //carry generated by the sum
          int pow=1;
         while(n1>0 || n2>0 || carr>0){
             int rem1=n1%10;
             int rem2=n2%10;
             n1=n1/10;
             n2=n2/10;

             int d=rem1 + rem2 + carr; //adding  the number with remaingng
             carr= d / b; //getting the number after deviding by the base
             int lastrem=d % b;     //getting the rhs value of the after addition

             rv+= lastrem * pow;  //multiplying the last rem with pow 10 to attain the right position
             pow=pow*10;

         }

        return rv;
    }

}
